name: Receptura akcji TypeScript
description:
  Odczekuje kilka milisekund, zapisuje niesamowite podsumowanie zadania na
  wyjściu przepływu pracy i zwraca bieżącą datę i godzinę.
author: Michal

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
